### ISSUE TITLE
the border not anti-alias ? 

### ISSUE THREAD

**Issue by eggcaker** [yako-dev/flutter_badges#98]
## Environment

**Package version:**  3.0.2
**Platform:** Android
**Device information:**  Android-17 

## Description
Check the screenshot, i have define a badge with a border(2), the border color is white, seem out side the border still has a very thin border, and color same as badget  color. 

## Images 
![1600662e5ee8dacd9589ac3c11effbc](https://user-images.githubusercontent.com/21374/215259816-86bc68fe-7979-4086-a4ff-72b49f52e42e.jpg)

Not sure it's anit-alias related issue

**Comment by yadaniyil** [comment]
Hey @eggcaker, please try this version of badges:
```
badges:
    git:
      url: https://github.com/yako-dev/flutter_badges
      ref: 98-fix/border-clip-behavior
```

Here is clipBehavior: Clip.hardEdge is applied. Please tell me if it's better.

**Comment by eggcaker** [comment]
@yadaniyil thanks , but seems looks like before
![微信图片_20230217065913](https://user-images.githubusercontent.com/21374/219507066-71870017-0df2-4049-8b05-7818404ffbc4.jpg)

**Comment by dawarepramod4** [comment]
yes same here..
![image](https://github.com/yako-dev/flutter_badges/assets/91264300/725ddb74-5ec8-4e97-ac55-e69fcfd33a06)

**Comment by M-ixai-L** [comment]
Hey @eggcaker and @dawarepramod4 , please try this version of badges:
```
badges:
    git:
      url: https://github.com/yako-dev/flutter_badges
      ref: 98-fix/border-stroke-align
```
Here is changed strokeAlign. Please tell me if it's better.
